comment:
  layout: "diff"
  behavior: default
  require_changes: true  # Avoid coverage comment if no files are changed.

coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        # basic
        target: auto
        threshold: 10%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
  ignore:
    - "examples"  # ignore folder and all its contents
    - "doc"  # ignore folder and all its contents
