# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

TWIN_STATUS_OK = 0
TWIN_STATUS_WARNING = 1
TWIN_STATUS_ERROR = 2
TWIN_STATUS_FATAL = 3

TWIN_VARPROP_OK = 10
TWIN_VARPROP_NOTDEFINED = 11
TWIN_VARPROP_NOTAPPLICABLE = 12
TWIN_VARPROP_INVALIDVAR = 13
TWIN_VARPROP_ERROR = 14

TD_SCHEMATIC_LOADED = 1000
TD_SCHEMATIC_LOAD_ERROR = 1001

TD_MODELS_LOADED = 1100
TD_MODELS_LOAD_ERROR = 1101

TD_SIMULATE_OK = 1200
TD_SIMULATE_WARNING = 1201
TD_SIMULATE_ERROR = 1201

TD_LICENSE_CHECKOUT_OK = 1300
TD_LICENSE_CHECKOUT_ERROR = 1301
TD_LICENSE_CHECKIN_OK = 1302
TD_LICENSE_CHECKIN_ERROR = 1303
TD_LICENSE_CHECKED_OUT = 1304
TD_LICENSE_NOT_CHECKED_OUT = 1305
TD_LICENSE_ENVIRONMENT_ERROR = 1306

TD_GET_RESULT_OK = 1400
TD_GET_RESULT_ERROR = 1401

TD_CLOSE_MODEL_OK = 1500
TD_CLOSE_MODEL_ERROR = 1501

TD_RESET_MODEL_OK = 1600
TD_RESET_MODEL_ERROR = 1601

TD_CLOSE_SCHEMATIC_OK = 1700
TD_CLOSE_SCHEMATIC_ERROR = 1701

TD_GET_STATISTICS_OK = 1800
TD_GET_STATISTICS_ERROR = 1801

TD_GET_LOG_CONTENTS_OK = 1900
TD_GET_LOG_CONTENTS_ERROR = 1901

TD_SET_PARAMETERS_OK = 2000
TD_SET_PARAMETERS_ERROR = 2001

TD_SET_INPUT_START_VALUES_OK = 2100
TD_SET_INPUT_START_VALUES_ERROR = 2101

INVALID_NODE_ID_ERROR = 2200
INVALID_LICENSE_CHECKIN_REQUEST = 2201

TD_ROM_VISUALIZATION_CHANGE_OK = 2300
TD_ROM_VISUALIZATION_CHANGE_ERROR = 2301

TD_GET_ROM_MODE_COEF_FILES_OK = 2310
TD_GET_ROM_MODE_COEF_FILES_ERROR = 2311
TD_GET_ROM_SNAPSHOT_FILES_OK = 2312
TD_GET_ROM_SNAPSHOT_FILES_ERROR = 2313

TD_GET_ROM_IMAGE_FILES_OK = 2320
TD_GET_ROM_IMAGE_FILES_ERROR = 2321

TD_SET_ROM_VISUALIZATION_DIRECTORY_OK = 2330
TD_SET_ROM_VISUALIZATION_DIRECTORY_ERROR = 2331

TD_GET_ROM_RESOURCE_DIR_OK = 2340
TD_GET_ROM_RESOURCE_DIR_ERROR = 2341

TD_PARAMETRIC_SWEEP_RETRIEVED = 2350

TD_UPDATE_SRCDATA_PCK_OK = 2400
TD_UPDATE_SRCDATA_PCK_ERROR = 2401

TD_EXTRACT_SCHEMATIC_OK = 2500
TD_EXTRACT_SCHEMATIC_ERROR = 2501

TD_UPDATE_SIMU_GET_RESULT_OK = 2600
TD_UPDATE_SIMU_GET_RESULT_ERROR = 2601

TD_GET_CLOUD_INPUT_NAMES_OK = 2700
TD_GET_CLOUD_INPUT_NAMES_ERROR = 2701

TD_GET_COMPONENT_INFO_OK = 2800
TD_GET_COMPONENT_INFO_ERROR = 2801

TD_SAVE_STATE_OK = 2900
TD_SAVE_STATE_ERROR = 2901

TD_LOAD_STATE_OK = 3000
TD_LOAD_STATE_ERROR = 3001

CLOSED = 10000
LOADED = 10001
INSTANTIATED = 10002
INITIALIZED = 10003
SIMULATING = 10004
