name: Labeler
on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - '../labels.yml'

permissions:
  contents: read  # default minimal permission

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  label-syncer:
    name: Syncer
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Set labels
    needs: [label-syncer]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    # Label based on modified files
    - name: Label based on changed files
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    # Label based on branch name
    - uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
      if: |
        startsWith(github.event.pull_request.head.ref, 'doc') || 
        startsWith(github.event.pull_request.head.ref, 'docs')
      with:
        labels: documentation
        github_token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
      if: |
        startsWith(github.event.pull_request.head.ref, 'maint') ||
        startsWith(github.event.pull_request.head.ref, 'no-ci') ||
        startsWith(github.event.pull_request.head.ref, 'ci')
      with:
        labels: maintenance
        github_token: "${{ secrets.GITHUB_TOKEN }}" 

    - uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
      if: startsWith(github.event.pull_request.head.ref, 'feat')
      with:
        labels: |
          enhancement
        github_token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8 # v1.1.0
      if: |
        startsWith(github.event.pull_request.head.ref, 'fix') ||
        startsWith(github.event.pull_request.head.ref, 'patch')
      with:
        labels: bug
        github_token: "${{ secrets.GITHUB_TOKEN }}"

  commenter:
    name: Commenter
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Suggest to add labels
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
      # Execute only when no labels have been applied to the pull request
      if: toJSON(github.event.pull_request.labels.*.name) == '{}'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please add one of the following labels to add this contribution to the Release Notes :point_down:
          - [bug](https://github.com/ansys/pytwin/pulls?q=label%3Abug+)
          - [documentation](https://github.com/ansys/pytwin/pulls?q=label%3Adocumentation+)
          - [enhancement](https://github.com/ansys/pytwin/pulls?q=label%3Aenhancement+)
          - [good first issue](https://github.com/ansys/pytwin/pulls?q=label%3Agood+first+issue)
          - [maintenance](https://github.com/ansys/pytwin/pulls?q=label%3Amaintenance+)
          - [release](https://github.com/ansys/pytwin/pulls?q=label%3Arelease+)
